name: Deploy Astro Site via rsync

on:
  workflow_call:
    inputs:
      target-path:
        required: true
        type: string
    secrets:
      SSH_USER:
        required: true
      SSH_HOST:
        required: true
      SSH_PRIVATE_KEY:
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: Build
        run: pnpm build

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Ensure target directory exists on remote
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            "mkdir -p '${{ inputs.target-path }}'"


      - name: Deploy via rsync
        run: |
          rsync -avz --delete -e "ssh -i ~/.ssh/id_ed25519" \
            ./dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ inputs.target-path }}

      - name: Reload Caddy (optional)
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            'sudo systemctl reload caddy'
